###docker-compose.yml
version: '2'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - /home/data/lab/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:  
    image: nextcloud
    ports:
      - 10080:80
    links:
      - db
    volumes:
      - /home/data/lab/nextcloud/www:/var/www/html
    restart: always
